package com.demoproject.dmn_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DateObject implements java.io.Serializable {
    
    static final long serialVersionUID = 1L;
    
	@org.kie.api.definition.type.Label(value = "projectDate")
	private java.lang.String projectDate;

	public DateObject() {
	}

	public java.lang.String getProjectDate() {
		return this.projectDate;
	}

	public void setProjectDate(java.lang.String projectDate) {
		this.projectDate = projectDate;
	}

	public DateObject(java.lang.String projectDate) {
		this.projectDate = projectDate;
	}
	
	@Override
    public String toString() {
        return "DateObject{" +
                "projectDate='" + projectDate + '\'' +
                '}';
    }

}