package com.demoproject.dmn_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ProjectDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "ProjectList")
	private java.util.List<com.demoproject.dmn_project.ProjectObject> ProjectList;
	@org.kie.api.definition.type.Label(value = "DateList")
	private java.util.List<com.demoproject.dmn_project.DateObject> DateList;

	public ProjectDetails() {
	}

	public java.util.List<com.demoproject.dmn_project.ProjectObject> getProjectList() {
		return this.ProjectList;
	}

	public void setProjectList(
			java.util.List<com.demoproject.dmn_project.ProjectObject> ProjectList) {
		this.ProjectList = ProjectList;
	}

	public java.util.List<com.demoproject.dmn_project.DateObject> getDateList() {
		return this.DateList;
	}

	public void setDateList(
			java.util.List<com.demoproject.dmn_project.DateObject> DateList) {
		this.DateList = DateList;
	}

	public ProjectDetails(
			java.util.List<com.demoproject.dmn_project.ProjectObject> ProjectList,
			java.util.List<com.demoproject.dmn_project.DateObject> DateList) {
		this.ProjectList = ProjectList;
		this.DateList = DateList;
	}

}