package com.demoproject.dmn_project;

import java.util.List;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ProjectRevenueList implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "ProjectRevenueList")
    private java.util.List<ProjectRevenueObject> ProjectRevenueList;

    public ProjectRevenueList() {
    }

    public List<ProjectRevenueObject> getProjectRevenueList() {
        return ProjectRevenueList;
    }

    public void setProjectRevenueList(List<ProjectRevenueObject> projectRevenueList) {
        ProjectRevenueList = projectRevenueList;
    }
}