package com.demoproject.dmn_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ProjectRevenueObject implements java.io.Serializable {
    
    static final long serialVersionUID = 1L;
    
	@org.kie.api.definition.type.Label(value = "ProjectRevenue")
	private java.lang.String projectRevenue;
	@org.kie.api.definition.type.Label(value = "NetWorkDays")
	private java.lang.String netWorkDays;
	@org.kie.api.definition.type.Label(value = "ProjectName")
	private java.lang.String projectName;

	public ProjectRevenueObject() {
	}

	public java.lang.String getProjectRevenue() {
		return this.projectRevenue;
	}

	public void setProjectRevenue(java.lang.String projectRevenue) {
		this.projectRevenue = projectRevenue;
	}

	public java.lang.String getNetWorkDays() {
		return this.netWorkDays;
	}

	public void setNetWorkDays(java.lang.String netWorkDays) {
		this.netWorkDays = netWorkDays;
	}

	public java.lang.String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(java.lang.String projectName) {
		this.projectName = projectName;
	}

	public ProjectRevenueObject(java.lang.String projectRevenue,
			java.lang.String netWorkDays, java.lang.String projectName) {
		this.projectRevenue = projectRevenue;
		this.netWorkDays = netWorkDays;
		this.projectName = projectName;
	}
	
	@Override
    public String toString() {
        return "ProjectRevenueObject{" +
                "ProjectRevenue='" + projectRevenue + '\'' +
                ", NetWorkDays=" + netWorkDays +
                ", ProjectName='" + projectName + '\'' +
                '}';
    }

}